### ISSUE TITLE
where licencs 

### ISSUE THREAD

**Issue by koushiroue** [FuadAbdullah/emergency_kursi#1]
wher

**Comment by FuadAbdullah** [comment]
what license, master

**Comment by koushiroue** [comment]
[bruhweoecmscs](http://choosealicense.com/)

**Comment by koushiroue** [comment]
[food for thought](https://islamqa.info/en/answers/102352/copying-programs-crack-and-serial)

**Comment by FuadAbdullah** [comment]
i am enlightened. thank you master

**Comment by koushiroue** [comment]
cool
